### ISSUE TITLE
How to add documentation to directives?

### ISSUE THREAD

**Issue by YasserAnsari** [ximenean/angular-styleguide#4]
Is there a guide for documentation in the code for directives?

**Comment by alj1s** [comment]
There are examples of JSDoc comments here: [Style y070](https://github.com/ximenean/angular-styleguide#style-y070)
And I've just added a section on JSDoc here: [Style y220](https://github.com/ximenean/angular-styleguide#style-y220)

Let me know if you want anything else.

**Comment by YasserAnsari** [comment]
Ah that's great. Thanks Andrew.
